# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn2'
    subscriptionId: '17f13149-57dd-4cba-b826-44ed6aee0b0b'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'chenyerg'
    location: 'China North 2'
    templateLocation: 'Linked artifact'
    overrideParameters: '-projectName RockboyforAzRmPipleline -linkedTemplateUri https://github.com/rockboyfor/AzureRmPipeline/blob/master/CreateAzureStorage/linkedStorageAccount.json'
    deploymentMode: 'Incremental'
    deploymentName: 'chenyetestdeployment'